export class User{
	constructor(){
		this.id = '0';
		this.phone = '';
		this.head_thumbnail = '';
		this.head_thumbnail_url = '';
		this.name = '';
		this.companyId = '';
		this.company = '';
		this.departmentId = '';
		this.department = '';
		this.position = '';
		this.contact = '';
		this.work_contact = '';
		this.mail = '';
		this.work_address = '';
		this.nickname = '';
		this.sex = '3';
		this.organizationFullName='';
		//this.birthday = new Date();
		this.home_address = '';
		this.qq_num = '';
		this.wechat_num = '';
		this.referrer_phonenum = '';
		this.referrerid='';
		this.referrer = '';
		this.name_card = '';
		this.name_card_url = '';
		this.info_card = '';
		this.info_card_url='';
		this.userStatus = '1';
		this.approveStatus = '3';
		this.mailModel = '1';
		this.visitModel = '1';
		this.backup = '';
		this.userType = '2';
	}
	id:string;
	info_card:string;
	info_card_url:string;
	phone:string;
	head_thumbnail:any;
	head_thumbnail_url:string;
	name:string;
	organizationFullName:string;
	companyId:string;
	company:string;
	departmentId:string;
	department:string;
	position:string;
	contact:string;
	work_contact:string;
	mail:string;
	work_address:string;
	nickname:string;
	sex:string;
	birthday:any;
	home_address:string;
	qq_num:string;
	wechat_num:string;
	referrer_phonenum:any;
	referrerid:string;
	referrer:string;
	name_card:string;
	name_card_url:string;
	userStatus:string;
	approveStatus:string;
	mailModel:string;
	visitModel:string;
	backup:string;
	userType:string;
	reset(){
		this.id = '0';
		this.phone = '';
		this.head_thumbnail = '';
		this.head_thumbnail_url = '';
		this.name = '';
		this.companyId = '';
		this.company = '';
		this.departmentId = '';
		this.department = '';
		this.position = '';
		this.contact = '';
		this.work_contact = '';
		this.mail = '';
		this.work_address = '';
		this.nickname = '';
		this.sex = '3';
		this.birthday ='';
		this.home_address = '';
		this.qq_num = '';
		this.wechat_num = '';
		this.referrer_phonenum = '';
		this.referrerid='';
		this.referrer = '';
		this.name_card = '';
		this.name_card_url = '';
		this.userStatus = '1';
		this.approveStatus = '3';
		this.mailModel = '1';
		this.visitModel = '1';
		this.backup = '';
		this.userType='2'
	}
}